title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: "/eumidion.com"
url: "https://eumidion.github.io"

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
quotes: false
sass:
  sourcemap: never
  
